# Generated by Django 5.1.3 on 2025-02-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='date_upd',
        ),
    ]
