# Generated by Django 5.1.3 on 2025-02-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='prix_total',
            field=models.FloatField(editable=False),
        ),
    ]
