# Generated by Django 5.1.3 on 2025-02-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='achat',
        ),
    ]
